name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # या आपकी default branch

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install Android Build Tools
        run: |
         yes | sdkmanager "build-tools;30.0.3" "platforms;android-30"
         echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip git build-essential \
            libssl-dev libffi-dev \
            python3-dev python3-pip \
            openjdk-17-jdk wget \
            libncurses5-dev \
            libstdc++6 \
            libz-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libfreetype6-dev \
            pkg-config \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libbz2-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev
          export PATH=$PATH:~/.local/bin/

      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools cython virtualenv
          pip install buildozer

      - name: Initialize buildozer (if .spec doesn't exist)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build the APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
