jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf automake libtool pkg-config \
            libffi-dev build-essential \
            zip unzip openjdk-17-jdk python3-pip git wget

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
          buildozer init || true  # in case buildozer.spec not already there
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: spyapp-apk
          path: bin/*.apk
