on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y autoconf automake libtool pkg-config libffi-dev build-essential
          sudo apt install -y libffi-dev autoconf automake build-essential pkg-config zip unzip openjdk-17-jdk python3-pip git
          pip install --upgrade pip
          pip install buildozer Cython==0.29.36

      - name: Set up Android SDK
        run: |
         mkdir -p $HOME/android-sdk/cmdline-tools
         cd $HOME/android-sdk/cmdline-tools
         curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
         unzip sdk-tools.zip -d tools
         yes | tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: spyapp-apk
          path: bin/*.apk
