name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool pkg-config libffi-dev \
            build-essential libssl-dev zlib1g-dev libbz2-dev \
            libreadline-dev libsqlite3-dev llvm ncurses-dev \
            libncurses5-dev libgdbm-dev libdb-dev libexpat1-dev \
            liblzma-dev libxml2-dev libxmlsec1-dev wget unzip

      - name: Install Buildozer & p4a
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.36
          pip install buildozer python-for-android

      - name: Install Android SDK
        run: |
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK using Buildozer
        env:
          ANDROID_SDK_ROOT: ${{ runner.home }}/android-sdk
          PATH: ${{ runner.home }}/android-sdk/cmdline-tools/tools/bin:$PATH
        run: |
          buildozer android debug

      - uses: actions/upload-artifact@v3
        with:
          name: spyapp-apk
          path: bin/*.apk
